### PR TITLE
utterances 1.0

### PR DESCRIPTION
**Pull request by jdanyow**
* Migrate build system to [parcel](https://parceljs.org/) :package: :rocket: 

* Switch from a classic [GitHub OAuth App](https://developer.github.com/apps/differences-between-apps/#about-oauth-apps) to the newer [GitHub App](https://developer.github.com/apps/differences-between-apps/#about-github-apps) authentication model.

  *:warning: Site owners must [install the Utterances GitHub App](https://github.com/apps/utterances) on the GitHub repo that hosts their comments.*

  The change was required for utterances to take advantage of the more granular permissions scheme offered by the GitHub App model.  With the current OAuth App, utterances must request the `public_repo` scope just to read/write issues and comments. A lot of extra permissions we don't need come along with this scope and users have raised issues (see #23). With the new app model, utterances will only have *read/write permissions on issues & comments in repos where the utterances app is installed*. 

* Inlines README.md during the build.

  Previously the html for the README.md file was loaded via a GitHub API call and inserted into the utteranc.es home page at run-time. This was a lazy hack, now that we're using parcel+posthtml it can be integrated in the build very easily.

### CODE REVIEW

**Comment by Eduard2799** [comment]
http://eduard.epizy.com/?i=1

**Comment by Eduard2799** [comment]
arce/prograweb-una

**Comment by JeffThorsen777** [comment]
Thanks!

**Comment by Stofcri** [comment]
No links on nvidia shield tv for Hanime.tv

**Comment by Stofcri** [comment]
Return Of The Max Doesn’t seems to work for me in Uk

**Comment by Stofcri** [comment]
DMW LIVE SPORTS Doesn’t seem to work in Uk 26 august 2023

**Comment by cashreedhar** [comment]
thanks

**Comment by khanzain4** [comment]
🚀 Exciting news! The migration to Parcel for the build system and the switch to the new GitHub App authentication model showcase a commitment to efficiency and enhanced user experience. The move to Utterances GitHub App not only streamlines authentication but also brings a more granular permissions scheme, addressing user concerns about unnecessary scopes. Kudos for the [thoughtful improvements](https://iqratechnology.com/academy/)! 🌟👏

**Comment by cdkao** [comment]
Crap addon.  Why is even listed.

**Comment by cdkao** [comment]
Is it possible to also add premiumize.me as another debrid alternative?

**Comment by emptypizza** [comment]
ㄴㅇㅊㅁㄴ

**Pull request merged**
