### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by kaknut**
Adding 'data-' prefix to remove w3c validator error.

Based upon https://github.com/utterance/utterances/issues/109#issuecomment-457964487 by @jdanyow 

Reference: https://validator.w3.org/nu/?showsource=yes&doc=https%3A%2F%2Futteranc.es

### CODE REVIEW

**Comment by kaknut** [comment]
Can we have a response or update on this please?
@jdanyow 
Though this isn't causing an operational issue but everyone loves a clean console log I guess.

**Comment by jdanyow** [comment]
Utterances permits folks to prefix the attributes with `data-` if they choose to do so. I do not plan to prefix them by default because there’s no real requirement.
https://html.spec.whatwg.org/multipage/syntax.html#syntax-attribute-name

Is the validator you're using up to date?

**Comment by techboyg5** [comment]
> Utterances permits folks to prefix the attributes with `data-` if they choose to do so. I do not plan to prefix them by default because there’s no real requirement.
> https://html.spec.whatwg.org/multipage/syntax.html#syntax-attribute-name
> 
> Is the validator you're using up to date?

It's the W3C official validator. When new standards are released, the validator is updated.

**Comment by kaknut** [comment]
> Utterances permits folks to prefix the attributes with `data-` if they choose to do so. I do not plan to prefix them by default because there’s no real requirement.
> https://html.spec.whatwg.org/multipage/syntax.html#syntax-attribute-name
> 
> Is the validator you're using up to date?

I know not using data attribute is ok just Chromium still hasn't updated it. Also I don't see any issues using aata prefix. Anyways it's personal choice.

**Pull request closed without merging**
