### PR TITLE
chore: Drop SITES.md for GitHub topic tag

### LINKED ISSUE #464: Separate SITES.md from this repository
Now the commit log and the pull requests are full of "Update SITES.md". We can view the commit log of the `src` directory, though.

I think it will be better if the SITES.md is in a different repository.

(Personally, I don't think it makes sense to allow everyone to add their site to a list which already consists of 151 items. The 3.7k stars speak well, and we only need some famous sites on the list. But that's another problem.)

### PR DESCRIPTION
**Pull request by nschonni**
Maybe there is a better topic tag, but I noticed that there are already some using it, and this drops the noise of people trying to update SITES.md

Closes #464

### CODE REVIEW

**Comment by nschonni** [comment]
@jdanyow does this make sense to you?

**Comment by jdanyow** [comment]
thanks for the PR. Shipped!

**Comment by nschonni** [comment]
No problem, guess you need a boilerplate message to close all the "Update SITE.md" PRs that are still open 😆

**Comment by nschonni** [comment]
Ha, realized it might be good to add the tag on this repo, so it will likely show at the top of the results https://github.com/topics/utterances

**Pull request merged**
