### PR TITLE
added theme: nella-red

### PR DESCRIPTION
**Pull request by allenfrostline**
New theme developed in order to make utterance comment area more consistent with my blog's overall theme. Changes in `yarn.lock` not necessarily need merging though.

### CODE REVIEW

**Comment by allenfrostline** [comment]
Hi can you review this PR? I need it approved before I can modify my website. Thank you!

**Comment by allenfrostline** [comment]
@jdanyow Hi can you merge this PR when you've got time plz? It's been half a month and my website updating is postponed basically because of lack of this theme for utterances. Allen 🤖

**Comment by allenfrostline** [comment]
HI @jdanyow can you review and approve this PR? It's been months...

**Comment by jdanyow** [comment]
requested changes (yarn.lock) have not been addressed.

**Comment by allenfrostline** [comment]
> requested changes (yarn.lock) have not been addressed.

Hi I think I've delete that file from commit. Can you explain why it's not addressed yet? Thanks

**Comment by nschonni** [comment]
image

You've got conflicts in 2 files. Probably need to do a rebase to resolve the issues. Probably editing the commits to remove the changes to the lock-file would be easiest

**Comment by allenfrostline** [comment]
Closing with another PR #422

**Pull request closed without merging**
